"""Verification of the entry points that had no tests at all.

Two command-line tools shipped with zero coverage: the TLS server and the test-vector
extractor. Both are things somebody running this project would actually invoke, and a project
whose pitch is verification cannot have entry points nobody ever executed. These are not deep
tests -- the logic underneath them is tested elsewhere -- they check that each tool parses its
arguments, does the thing, and fails comprehensibly rather than with a traceback.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import numpy as np
import pytest

from esm446.cli import cot_server, extract_vector

# --------------------------------------------------------------------------------------
# The TLS server
# --------------------------------------------------------------------------------------


@pytest.fixture
def certificate(tmp_path: Path) -> tuple[Path, Path]:
    import shutil

    if not shutil.which("openssl"):
        pytest.skip("openssl is not installed")
    cert, key = tmp_path / "cot.crt", tmp_path / "cot.key"
    subprocess.run(
        [
            "openssl",
            "req",
            "-x509",
            "-newkey",
            "rsa:2048",
            "-nodes",
            "-days",
            "1",
            "-keyout",
            str(key),
            "-out",
            str(cert),
            "-subj",
            "/CN=localhost",
        ],
        capture_output=True,
        check=True,
    )
    return cert, key


def test_the_server_reports_a_missing_certificate_rather_than_a_traceback(tmp_path: Path) -> None:
    """The first thing anybody hits, because the certificate has to be generated by hand."""
    status = cot_server.main(
        ["--cert", str(tmp_path / "absent.crt"), "--key", str(tmp_path / "absent.key")]
    )

    assert status == 1


def test_the_server_broadcasts_what_it_reads_from_stdin(
    certificate: tuple[Path, Path], monkeypatch: pytest.MonkeyPatch, capsys
) -> None:
    """The mode that makes it testable by hand: pipe stored events in, watch iTAK draw them."""
    import io
    import socket
    import ssl
    import threading

    cert, key = certificate
    received: list[bytes] = []
    ready = threading.Event()

    # A port the operating system picks, so the test cannot collide with anything.
    probe = socket.socket()
    probe.bind(("127.0.0.1", 0))
    port = probe.getsockname()[1]
    probe.close()

    def client() -> None:
        ready.wait(timeout=5.0)
        context = ssl.create_default_context()
        context.check_hostname = False
        context.verify_mode = ssl.CERT_NONE
        for _ in range(50):
            try:
                with context.wrap_socket(socket.create_connection(("127.0.0.1", port), 2.0)) as s:
                    s.settimeout(4.0)
                    received.append(s.recv(65535))
                return
            except OSError:
                threading.Event().wait(0.05)

    thread = threading.Thread(target=client, daemon=True)
    thread.start()

    # Hold stdin open until the client has connected, or the server broadcasts to nobody.
    class SlowStdin(io.StringIO):
        def __iter__(self):
            ready.set()
            threading.Event().wait(1.0)
            return iter(["<event uid='test'/>\n"])

    monkeypatch.setattr("sys.stdin", SlowStdin())

    status = cot_server.main(
        [
            "--cert",
            str(cert),
            "--key",
            str(key),
            "--host",
            "127.0.0.1",
            "--port",
            str(port),
            "--stdin",
        ]
    )
    thread.join(timeout=6.0)

    assert status == 0
    assert received and b"test" in received[0]


def test_the_server_binds_loopback_by_default() -> None:
    """A sensor feed reachable from every interface the moment somebody starts it."""
    parser_default = cot_server.main.__doc__ is not None
    assert parser_default

    import argparse
    import inspect

    source = inspect.getsource(cot_server.main)
    assert '"--host",\n        default="127.0.0.1"' in source or 'default="127.0.0.1"' in source
    assert "0.0.0.0" not in source.split("default=")[1].split(",")[0]
    del argparse


# --------------------------------------------------------------------------------------
# The test-vector extractor
# --------------------------------------------------------------------------------------


def write_capture(path: Path, seconds: float = 0.2, rate: float = 2_000_000.0) -> Path:
    """A small cs8 capture with a tone in it, standing in for a wideband recording."""
    samples = int(seconds * rate)
    t = np.arange(samples) / rate
    tone = 0.4 * np.exp(2j * np.pi * (446_093_750.0 - 446_593_750.0) * t)
    noise = 0.02 * (np.random.default_rng(0).standard_normal(samples) * (1 + 1j))
    iq = (tone + noise).astype(np.complex64)
    np.clip(iq.view(np.float32) * 127, -127, 127).astype(np.int8).tofile(path)
    return path


def test_the_extractor_cuts_shifts_and_decimates(tmp_path: Path) -> None:
    capture = write_capture(tmp_path / "capture.cs8")

    samples = extract_vector.extract(
        source_path=capture,
        start_s=0.0,
        duration_s=0.1,
        source_centre_hz=446_593_750.0,
        source_rate_hz=2_000_000.0,
        source_format="cs8",
    )

    assert samples.dtype == np.complex64
    assert len(samples) == pytest.approx(0.1 * extract_vector.VECTOR_SAMPLE_RATE_HZ, rel=0.02)


def test_the_extractor_removes_the_receivers_dc_offset(tmp_path: Path) -> None:
    """Skipping this aliases the local-oscillator spur onto a channel when decimating."""
    capture = write_capture(tmp_path / "capture.cs8")

    samples = extract_vector.extract(
        source_path=capture,
        start_s=0.0,
        duration_s=0.1,
        source_centre_hz=446_593_750.0,
        source_rate_hz=2_000_000.0,
        source_format="cs8",
    )

    assert abs(complex(samples.mean())) < 0.05


def test_the_extractor_refuses_a_span_the_file_does_not_hold(tmp_path: Path) -> None:
    capture = write_capture(tmp_path / "capture.cs8", seconds=0.05)

    with pytest.raises(ValueError, match="holds"):
        extract_vector.extract(
            source_path=capture,
            start_s=0.0,
            duration_s=10.0,
            source_centre_hz=446_593_750.0,
            source_rate_hz=2_000_000.0,
            source_format="cs8",
        )


def test_the_extractor_refuses_a_non_integer_decimation(tmp_path: Path) -> None:
    capture = write_capture(tmp_path / "capture.cs8")

    with pytest.raises(ValueError, match="integer decimation"):
        extract_vector.extract(
            source_path=capture,
            start_s=0.0,
            duration_s=0.05,
            source_centre_hz=446_593_750.0,
            source_rate_hz=1_234_567.0,
            source_format="cs8",
            target_rate_hz=500_000.0,
        )


def test_the_extractor_writes_a_vector_beside_its_description(tmp_path: Path) -> None:
    """The sidecar is what lets a replayed vector report when the signal happened."""
    samples = (np.arange(1000) / 1000).astype(np.float32).view(np.complex64)

    iq_path, metadata_path = extract_vector.write_vector(
        samples, tmp_path / "vector", {"note": "unit test", "start_time": 1.0}
    )

    assert iq_path.suffix == ".cs8"
    payload = json.loads(metadata_path.read_text())
    assert payload["note"] == "unit test"
    assert payload["scale_peak"] > 0


def test_the_extractor_normalises_before_quantising(tmp_path: Path) -> None:
    """Writing a weak extract without scaling buries it in the bottom few codes of cs8.

    Checked on the magnitude rather than on either component: a sample at 45 degrees puts
    127/sqrt(2) = 90 in each of I and Q while still being full scale, so a per-component
    threshold would measure the signal's phase as much as its level.
    """
    weak = (1e-4 * np.ones(1000, dtype=np.float32)).view(np.complex64)

    iq_path, _ = extract_vector.write_vector(weak, tmp_path / "vector", {})

    written = np.fromfile(iq_path, dtype=np.int8).astype(np.float32).view(np.complex64)
    assert np.abs(written).max() > 120
